from __future__ import annotations

from typing import Protocol, runtime_checkable

from wyvern.contracts import Health, Position, Velocity, Waypoint


@runtime_checkable
class VehicleAdapter(Protocol):
    vehicle_id: str

    async def connect(self) -> None: ...
    async def is_connected(self) -> bool: ...
    async def arm(self) -> None: ...
    async def disarm(self) -> None: ...
    async def upload_mission(self, waypoints: list[Waypoint]) -> None: ...
    async def start_mission(self) -> None: ...
    async def pause_mission(self) -> None: ...
    async def hold(self) -> None: ...
    async def return_to_launch(self) -> None: ...
    async def land(self) -> None: ...

    async def get_position(self) -> Position: ...
    async def get_velocity(self) -> Velocity: ...
    async def get_battery_percent(self) -> float: ...
    async def get_flight_mode(self) -> str: ...
    async def get_health(self) -> Health: ...
    async def is_armed(self) -> bool: ...
    async def is_in_air(self) -> bool: ...
    async def get_mission_progress(self) -> tuple[int, int]: ...
